services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bangla-tts-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/audio:/app/audio
      - ./backend/logs:/app/logs
      - huggingface_cache:/root/.cache/huggingface
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - HF_HOME=/root/.cache/huggingface
    networks:
      - tts-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 180s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bangla-tts-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - tts-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  tts-network:
    driver: bridge

volumes:
  huggingface_cache:
    driver: local
